import { card, insight, meter, metric, table } from './components.js'

const action = (label, event, primary = true) => `<button class="${primary ? 'primary' : 'secondary'}" data-action="${event}">${label}</button>`
const chart = (values) => `<div class="chart">${values.map((value) => `<i style="height:${value}%"></i>`).join('')}</div>`
const page = (eyebrow, title, description, body) => `<section><div class="eye">${eyebrow}</div><h1 class="title">${title}</h1>${description ? `<p class="sub">${description}</p>` : ''}${body}</section>`

export function dashboard(state) {
  const date = new Intl.DateTimeFormat([], { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date())
  return page(`Mission briefing · ${date}`, `Good morning, <span data-athlete-name>${state.name}</span>.`, 'Training, recovery, nutrition, and performance signals are synchronized into today’s operating plan.', `
    <section class="card hero"><div class="hero-grid"><div><span class="mission">MISSION READY</span><h2>${state.mission}</h2><p class="muted">${state.adjusted ? 'Volume reduced 10% and compound rest extended. Estimated completion is now 54 minutes.' : 'Recovery supports normal training. Prioritize controlled pressing volume and finish inside the recommended recovery window.'}</p><div class="metrics"><div class="metric"><b>${state.readiness}%</b><span>Recovery</span></div><div class="metric"><b>HIGH</b><span>Readiness</span></div><div class="metric"><b>61 min</b><span>Duration</span></div><div class="metric"><b>7–10:30</b><span>Recovery window</span></div></div><div class="actions">${action('Begin mission', 'go:workout')}${action('Adjust with AI', 'adjust', false)}</div></div><div class="ring" style="--readiness:${state.readiness}"><div><strong>${state.readiness}</strong><span>MISSION READY</span></div></div></div></section>
    <div class="grid g12 spacer">${metric('Sleep', '8h 07m', '↑ 34m')}${metric('HRV', '67 ms', '↑ 6%')}${metric('Strain', '6.8', 'Optimal')}${metric('Weight', '205.2', 'Stable')}</div>
    <div class="grid g12 spacer">${card('AI Insights', insight('↗', 'Pressing strength is accelerating', 'Last week’s incline top set supports a suggested opening set of 240 × 8.') + insight('◷', 'Leg frequency needs attention', 'No direct leg session has been logged for eight days.') + insight('✦', 'Sleep-response correlation detected', 'Your strongest sessions follow at least eight hours of sleep.'), 's8')}${card('Muscle balance', ['Chest', 'Back', 'Shoulders', 'Legs', 'Arms'].map((name, index) => meter(name, [82, 66, 73, 48, 79][index])).join(''), 's4')}</div>`)
}

export function workout() {
  const exercises = [['01', 'Incline Barbell Press', '4 × 6–8', '240 × 8'], ['02', 'Flat Dumbbell Press', '3 × 8–10', '95 × 10'], ['03', 'Cable Fly', '3 × 12–15', 'RPE 8'], ['04', 'Weighted Dip', '3 × 8–10', '+70 lb'], ['05', 'Rope Pressdown', '4 × 10–15', '60 sec']]
  const list = exercises.map(([number, name, sets, target]) => `<article class="exercise"><div class="num">${number}</div><div><b>${name}</b><small>${sets}</small></div><span class="tag">${target}</span></article>`).join('')
  return page('Today’s mission', 'Upper Body Hypertrophy', 'AI-adjusted for recovery, recent performance, equipment, and time.', `<div class="grid g12">${card('Active plan', `${list}<div class="actions">${action('Start workout', 'toast:Workout started · adaptive timer active')}${action('Smart warmups', 'toast:Warmups: 45×12, 95×8, 145×5, 185×3, 215×1', false)}</div>`, 's8')}${card('Fatigue prediction', `<div class="big">7.4 RPE</div>${meter('Chest', 86)}${meter('Triceps', 71)}${meter('Shoulders', 43)}${meter('Systemic', 58)}${insight('◷', 'Adaptive rest', '2:45 compounds · 1:15 isolation.')}`, 's4')}</div><div class="grid g12 spacer">${card('Live volume', meter('Chest', 72) + meter('Triceps', 46) + meter('Shoulders', 31) + meter('Total', 61))}${card('Projected score', table(['', ''], [['Strength', '88'], ['Hypertrophy', '92'], ['Volume', '84'], ['Recovery cost', '67'], ['Overall grade', 'A−']]))}</div>`)
}

export function analytics() {
  return page('Performance intelligence', 'Analytics', 'Recovery, strength, volume, and body signals translated into decisions.', `<div class="grid g12">${card('Strength forecast', `${chart([44, 53, 49, 62, 68, 72, 78, 85, 91, 96])}<p class="muted">Projected incline press 1RM: <b class="light">312 lb</b> within 8–10 weeks.</p>`, 's8')}${card('Recovery trend', `<div class="big">+7.2%</div>${meter('Sleep', 84)}${meter('HRV', 78)}${meter('RHR', 91)}${meter('Consistency', 69)}`, 's4')}</div><div class="grid g12 spacer">${card('Muscle heat map', `<div class="heat">${[['Chest', 82], ['Back', 65], ['Delts', 74], ['Biceps', 68], ['Triceps', 79], ['Quads', 43], ['Hams', 48], ['Glutes', 51], ['Calves', 35], ['Core', 57]].map(([name, value]) => `<div class="muscle" style="--heat:${value / 100}">${name}</div>`).join('')}</div>`)}${card('Weekly AI report', insight('✓', 'Win', 'Pressing volume increased 8% without reduced readiness.') + insight('!', 'Weakness', 'Posterior-chain frequency remains below target.') + insight('→', 'Recommendation', 'Advance the next leg mission one day and cap RPE at 8.'))}</div>`)
}

export function nutrition() { return page('Fuel system', 'Nutrition', 'Calories, macros, hydration, supplements, and meal decisions aligned to the mission.', `<div class="grid g12">${card('Daily target', `<div class="big">2,860</div><p class="muted">1,940 consumed · 920 remaining</p>${meter('Protein', 84)}${meter('Carbs', 65)}${meter('Fat', 80)}${meter('Hydration', 74)}`, 's4')}${card('Meal log', `${table(['Meal', 'Calories', 'Protein'], [['Eggs, oats, berries', '620', '46g'], ['Chicken rice bowl', '790', '61g'], ['Pre-workout shake', '310', '34g']])}<div class="actions">${action('Scan barcode', 'toast:Barcode camera ready')}${action('Add meal', 'toast:Meal added', false)}</div>`, 's8')}</div>`) }

export function body() { return page('Body composition', 'Digital physique', 'Measurements, DEXA history, progress photos, and estimated composition.', `<div class="grid g12">${metric('Weight', '205.2 lb', '−1.8 lb')}${metric('Body fat', '14.8%', '−0.6%')}${metric('Lean mass', '174.8 lb', '+0.4 lb')}${metric('Waist', '34.8 in', '−0.5 in')}</div><div class="grid g12 spacer">${card('Composition trend', chart([74, 72, 70, 68, 67, 65, 64, 62, 60, 59]), 's8')}${card('Measurements', `${table(['', ''], [['Chest', '44.5 in'], ['Arms', '16.4 in'], ['Thighs', '25.2 in'], ['Waist', '34.8 in']])}${action('Add check-in', 'toast:Check-in opened')}`, 's4')}</div>`) }

export function trainer() { return page('Autonomous programming', 'AI Trainer', 'Generate training from history, recovery, equipment, weak points, injuries, and available time.', `<div class="grid g12">${card('Generate mission', `<div class="form"><label>Available time<select><option>45 minutes</option><option selected>60 minutes</option></select></label><label>Equipment<select><option>Full gym</option><option>Hotel gym</option></select></label></div><label>Instruction<textarea placeholder="Build a 45-minute push workout and protect my right shoulder."></textarea></label>${action('Generate workout', 'toast:Custom mission generated')}`, 's8')}${card('AI memory', ['Favorite: incline press', 'Rep range: 6–12', 'Avoid: upright rows', 'Evening training', 'Goal: strength + size', 'Full commercial gym'].map((item) => insight('•', item)).join(''), 's4')}</div>`) }

export function library() { const names = ['Incline Press', 'Hack Squat', 'Chest-Supported Row', 'Romanian Deadlift', 'Lateral Raise', 'Weighted Dip', 'Bayesian Curl', 'Leg Extension']; return page('Movement intelligence', 'Exercise Library', 'Technique, muscles, fatigue cost, strength curve, difficulty, equipment, and alternatives.', `<div class="grid g12">${names.map((name, index) => card('', `<span class="tag">${index < 4 ? 'Compound' : 'Accessory'}</span><h2>${name}</h2><p class="muted">Primary movement intelligence and video slot.</p>${meter('Fatigue', [74, 82, 65, 88, 28, 76, 24, 33][index])}${action('View', 'toast:Exercise intelligence opened', false)}`, 's3')).join('')}</div>`) }

export function records() { return page('Milestones', 'Records & Rank', 'Automatic PR detection, estimated maxes, XP, streaks, and achievements.', `<div class="grid g12">${card('Recent records', table(['Exercise', 'Record', 'Type'], [['Incline Press', '235 × 8', 'Rep PR'], ['Hack Squat', '450 × 10', 'Volume PR'], ['Weighted Dip', '+90 × 7', 'Load PR']]), 's8')}${card('Season rank', `<div class="big">LVL 18</div><p class="muted">Vanguard III · 2,340 / 3,000 XP</p>${meter('Level progress', 78)}`, 's4')}</div><div class="badges spacer">${[['🏆', '100 sessions'], ['⚡', '4-week streak'], ['◆', '1M lb volume'], ['◈', 'Recovery master'], ['⬡', 'Early operator'], ['✦', '10 PR month'], ['◇', 'Coach verified'], ['◉', 'Nutrition streak']].map(([icon, label]) => `<div class="badge"><span>${icon}</span><b>${label}</b></div>`).join('')}</div>`) }

export function social() { return page('Optional network', 'Team & Challenges', '', `<div class="grid g12">${card('July Volume Offensive', `<div class="big">12 operators</div>${table(['Rank', 'Athlete', 'Volume'], [['1', 'Chase', '412,850 lb'], ['2', 'Marcus', '398,200 lb'], ['3', 'Jordan', '367,440 lb']])}`, 's8')}${card('Privacy', `<p class="muted">Private by default. Share per workout.</p>${action('Share mission', 'toast:Share composer opened')}`, 's4')}</div>`) }

export function coach() { return page('Coach operating center', 'Athlete Command', 'Readiness, compliance, alerts, programming, and notes.', `<div class="grid g12">${card('', table(['Athlete', 'Readiness', 'Compliance', 'Alert'], [['Chase Frith', '82%', '94%', 'None'], ['Demo Athlete', '54%', '76%', 'Sleep debt']]), 's8')}${card('Coach note', `<textarea placeholder="Private coaching note…"></textarea>${action('Save note', 'toast:Coach note queued')}`, 's4')}</div>`) }

export const views = { dashboard, workout, analytics, nutrition, body, trainer, library, records, social, coach }
